<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SmartGuard.Notifications.Microservice-af009ac8-a742-47b1-8ab6-aa427426a364</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-preview.1.25120.3" />
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="FirebaseAdmin" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartGuard.Model\SmartGuard.Model.csproj" />
  </ItemGroup>
</Project>
