services:
  smartguard.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:8080
      Kestrel__Endpoints__Grpc__Url: http://0.0.0.0:8081
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=${SQLSERVER_DB};User Id=sa;Password=${SQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      RabbitMQ__VirtualHost: ${RABBITMQ_VHOST}
      Redis__Configuration: redis:6379,password=${REDIS_PASSWORD}
      Archive__BaseUrl: http://smartguard.archive.microservice:8080
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  smartguard.archive.microservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__ArchiveDatabase: Server=sqlserver,1433;Database=${SQLSERVER_DB};User Id=sa;Password=${SQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      RabbitMQ__VirtualHost: ${RABBITMQ_VHOST}
      SmartGuardApi__BaseUrl: http://smartguard.api:8080
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  smartguard.notifications.microservice:
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__NotificationsDatabase: Server=sqlserver,1433;Database=${SQLSERVER_DB};User Id=sa;Password=${SQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      RabbitMQ__VirtualHost: ${RABBITMQ_VHOST}
      Redis__Configuration: redis:6379,password=${REDIS_PASSWORD}
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  smartguard.vectormatching.microservice:
    environment:
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      RabbitMQ__VirtualHost: ${RABBITMQ_VHOST}
      Grpc__ApiAddress: http://smartguard.api:8081